//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasOrganosCortes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int detal_prod { get; set; }
        public int detal_comp_id { get; set; }
        public int detal_prod_id { get; set; }
        public int detal_serv_id { get; set; }
        public int detal_sang_id { get; set; }
    
        public virtual Orden_Compra Orden_Compra { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Sangre Sangre { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
